const express = require('express')
const bodyParser = require('body-parser')
const api = require('./router/api')
const cors = require('cors')
const passport = require('passport')
const http = require('http')
const socketIO = require('socket.io')

const app = express()
const server = http.Server(app)
app.use(cors())
app.use(bodyParser.json())
var expressSession = require('express-session')
app.use(expressSession({secret: 'mySecretKey'}))
app.use(passport.initialize())
app.use(passport.session())
app.use('/api', api)

const io = socketIO(server)
const initSocket = require('./router/socket')
initSocket(io)

server.listen(3000, () => console.log('Server running on port: 3000'))
